### ISSUE TITLE
[Feature request] Change folder location without rehashing

### ISSUE THREAD

**Issue by nls44** [airdcpp/airdcpp-core#4]
It'd be nice if we could update the folder location of a shared folder without having to rehash. I'd like to use such functionality in the web API. 

Use case: I use one of the new extensions (https://github.com/zersetz-end/airdcpp-runscript-extension) to run a script based on the   "/queue/listeners/queue_bundle_status" event. Once my download has finished I move it to a different location depending on which folder I initially downloaded it to. For example, I download to /mnt/share/incoming/TV/ and upon completion I move the downloaded release to /mnt/TV/. For now, I send a refresh share command for the new path, but ideally I could just use the TTH that was already calculated.

**Comment by maksis** [comment]
See https://airdcpp.docs.apiary.io/#reference/hashing/methods/rename-path

New Linux builds will be out later today.

ps. API-related issues should be posted to https://github.com/airdcpp-web/airdcpp-webclient/issues
